# Generated by Django 4.2 on 2023-07-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpDownShare', '0003_remove_folder_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
