# Generated by Django 4.2 on 2023-07-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpDownShare', '0004_folder_can_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuserrelationship',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='fileuserrelationship',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='folderuserrelationship',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='folderuserrelationship',
            name='can_edit',
        ),
    ]
