# Generated by Django 4.2 on 2023-08-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UpDownShare', '0005_remove_fileuserrelationship_can_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UpDownShare.folder'),
        ),
    ]
