# Generated by Django 4.2 on 2023-08-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpDownShare', '0006_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuserrelationship',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
